pub mod api_commands;
pub mod changelog;
pub mod data;
pub mod data_commands;
pub mod folder_commands;
pub mod memo_commands;
pub mod open_folder_commands;
pub mod patreon_cache;
pub mod preferences_commands;
pub mod sort_commands;
pub mod task;
pub mod update;
pub mod util_commands;
pub mod world_status_commands;

use tauri_specta::{collect_commands, Builder};

pub fn generate_tauri_specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        data_commands::fetch_patreon_data,
        patreon_cache::fetch_patreon_vrchat_names,
        data_commands::fetch_blacklist,
        changelog::get_changelog,
        task::get_task_status,
        task::cancel_task_request,
        task::get_task_error,
        update::check_for_update,
        update::download_update,
        update::install_update,
        update::do_not_notify_update,
        folder_commands::add_world_to_folder,
        folder_commands::add_worlds_to_folder,
        folder_commands::remove_world_from_folder,
        folder_commands::hide_world,
        folder_commands::unhide_world,
        folder_commands::get_folders,
        folder_commands::create_folder,
        folder_commands::delete_folder,
        folder_commands::move_folder,
        folder_commands::rename_folder,
        folder_commands::set_folder_color,
        folder_commands::get_worlds,
        folder_commands::get_all_worlds,
        folder_commands::get_unclassified_worlds,
        folder_commands::get_hidden_worlds,
        folder_commands::get_tags_by_count,
        folder_commands::get_authors_by_count,
        folder_commands::delete_world,
        folder_commands::get_folders_for_world,
        folder_commands::share_folder,
        folder_commands::update_folder_share,
        folder_commands::download_folder,
        preferences_commands::get_theme,
        preferences_commands::set_theme,
        preferences_commands::get_language,
        preferences_commands::set_language,
        preferences_commands::get_card_size,
        preferences_commands::set_card_size,
        preferences_commands::get_region,
        preferences_commands::set_region,
        preferences_commands::get_starred_filter_items,
        preferences_commands::set_starred_filter_items,
        preferences_commands::get_folder_removal_preference,
        preferences_commands::set_folder_removal_preference,
        preferences_commands::get_update_channel,
        preferences_commands::set_update_channel,
        preferences_commands::get_sort_preferences,
        preferences_commands::set_sort_preferences,
        preferences_commands::get_default_instance_type,
        preferences_commands::set_default_instance_type,
        preferences_commands::get_visible_buttons,
        preferences_commands::set_visible_buttons,
        api_commands::try_login,
        api_commands::login_with_credentials,
        api_commands::login_with_2fa,
        api_commands::logout,
        api_commands::get_favorite_worlds,
        api_commands::get_world,
        api_commands::check_world_info,
        api_commands::get_recently_visited_worlds,
        api_commands::search_worlds,
        api_commands::create_world_instance,
        api_commands::get_user_groups,
        api_commands::get_permission_for_create_group_instance,
        api_commands::create_group_instance,
        api_commands::open_instance_in_client,
        open_folder_commands::open_logs_directory,
        open_folder_commands::open_folder_directory,
        data::read_data_commands::require_initial_setup,
        data::read_data_commands::check_files_loaded,
        data::read_data_commands::detect_old_installation,
        data::read_data_commands::pass_paths,
        data::read_data_commands::check_existing_data,
        data::read_data_commands::get_backup_metadata,
        data::read_data_commands::get_migration_metadata,
        data::write_data_commands::create_empty_auth,
        data::write_data_commands::create_empty_files,
        data::write_data_commands::create_backup,
        data::write_data_commands::restore_from_backup,
        data::write_data_commands::export_to_portal_library_system,
        data::write_data_commands::migrate_old_data,
        data::write_data_commands::delete_data,
        data::write_data_commands::export_native_data,
        memo_commands::get_memo,
        memo_commands::set_memo_and_save,
        memo_commands::search_memo_text,
        world_status_commands::set_world_photographed,
        world_status_commands::set_world_shared,
        world_status_commands::set_world_favorite,
        sort_commands::sort_worlds_display,
        util_commands::resolve_redirects,
        util_commands::get_startup_deep_link,
    ])
}
