import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';

import '@/app/globals.css';
import { LocalizationContextProvider } from '@/components/localization-context';
import { UpdateDialogProvider } from '@/components/UpdateDialogContext';
import { DeepLinkProvider } from '@/components/deep-link-provider';
import { PatreonProvider } from '@/contexts/patreon-context';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <DeepLinkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LocalizationContextProvider>
              <UpdateDialogProvider>
                <PatreonProvider>
                  <main>{children}</main>
                </PatreonProvider>
              </UpdateDialogProvider>
            </LocalizationContextProvider>
          </ThemeProvider>
          <Toaster richColors />
        </DeepLinkProvider>
      </body>
    </html>
  );
}
